import styled, { keyframes } from 'styled-components'
import { colors } from '../../styles/themes'

export const load = keyframes`
  0% { opacity: 1 }
  100% { opacity: 0 }
`

export const Container = styled.div``
export const Inner = styled.div`
  & div {
    left: 40%;
    top: 40%;
    position: absolute;
    animation: ${load} linear 1s infinite;
    background: #ffffff;
    width: 2.01px;
    height: 14.069999999999999px;
    border-radius: 0px / 0px;
    transform-origin: 1.005px 35.175px;
  }
  & div:nth-child(1) {
    transform: rotate(0deg);
    animation-delay: -0.875s;
    background: #ffffff;
  }
  & div:nth-child(2) {
    transform: rotate(45deg);
    animation-delay: -0.75s;
    background: #ffffff;
  }
  & div:nth-child(3) {
    transform: rotate(90deg);
    animation-delay: -0.625s;
    background: #ffffff;
  }
  & div:nth-child(4) {
    transform: rotate(135deg);
    animation-delay: -0.5s;
    background: #ffffff;
  }
  & div:nth-child(5) {
    transform: rotate(180deg);
    animation-delay: -0.375s;
    background: #ffffff;
  }
  & div:nth-child(6) {
    transform: rotate(225deg);
    animation-delay: -0.25s;
    background: #ffffff;
  }
  & div:nth-child(7) {
    transform: rotate(270deg);
    animation-delay: -0.125s;
    background: #ffffff;
  }
  & div:nth-child(8) {
    transform: rotate(315deg);
    animation-delay: 0s;
    background: #ffffff;
  }
`

/*.loadingio-spinner-spinner-p8in7axtw68 {
  width: 201px;
  height: 201px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}*/
/*.ldio-kww7cg5u24 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /!* see note above *!/
}
.ldio-kww7cg5u24 div { box-sizing: content-box; }*/
/* generated by https://loading.io/ */
